spring:
  datasource:
    url: jdbc:mysql://localhost:3306/llmtest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: dl765677
    driver-class-name: com.mysql.cj.jdbc.Driver
  banner:
    location: classpath:banner.txt
    charset: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 启用MyBatis-Plus的枚举处理
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    # 配置逻辑删除
    logic-delete-field: isDeleted
    logic-not-delete-value: 0
    logic-delete-value: 1
springdoc:
  api-docs:
    enabled: true
  path-provider: spring