spring:
  datasource:
    url: jdbc:mysql://localhost:3306/llmtest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: dl765677
    driver-class-name: com.mysql.cj.jdbc.Driver

  banner:
    location: classpath:banner.txt
    charset: utf-8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl